refactor: :recycle: restructure how data is loaded to home and other …
maxiggle/psk-wallet pull request #1
Opened 2023-10-28 20:09 UTC by maxiggle

2023-10-29 07:50 UTC, peteruche21 requested changes
It would be nice if you used the already available token and transaction class already available in the alchemy api module.

So we don't have to manually extract the fields we want into another class.

Look through the alchemy token and transactions module and use the fields you need to

2023-10-29 13:26 UTC, maxiggle commented
Okay
Got it

2023-11-02 14:57 UTC, peteruche21 commented on lib/app/providers/persist_auth_data.dart
you reviewed [#6](https://github.com/vaariance/vaariance-dart/commit/b1858c61dd3deed89c20c784f6b6df457f2023cd) in variance sdk but you didn't read the code.

this file is useless, because. what you are trying to achieve here was done in #6

2023-11-02 14:59 UTC, peteruche21 commented on lib/app/providers/wallet_provider.dart
you are still depending on Covalent API, when the module has been deleted on variance sdk.

you were meant to migrate to alchemyAPI. you can take a look at the sdk to find the differences and how to specifically work with the api.

2023-11-02 15:00 UTC, peteruche21 commented on lib/app/providers/home_provider.dart
you are still depending on Covalent API, when the module has been deleted on variance sdk.

you were meant to migrate to alchemyAPI. you can take a look at the sdk to find the differences and how to specifically work with the api.

2023-11-02 15:03 UTC, peteruche21 commented on lib/app/screens/create_account.dart
in the same #6 of variance sdk, the createAccount has been simplified. there is a get account address function that returns the exact address that will be set by the createAccount when called latter.

you can use that to get the account address. before calling create account.

2023-11-02 15:06 UTC, peteruche21 commented on lib/app/screens/transaction.dart
you are still dependent on custom transactionData which was specifically made for Covalent API. however you were meant to use the transaction object that comes directly from the alchemyAPI module to avoid unnecessary casting or mapping from api response into a transactionData object

2023-11-02 15:07 UTC, peteruche21 commented on lib/app/screens/token_balance.dart
you are still dependent on a custom TokenData object when you are meant to use the Token object that comes from the alchemyApi module which is the response type you get from alchemyAPI

2023-11-02 15:09 UTC, peteruche21 requested changes
please update data, pub spec, repo name to reflect variance. and fix the highlighted changes requested

2023-11-09 01:08 UTC, merged